


GET http://localhost:4040/api/health-check

### GET AUTH LINK

GET http://localhost:4040/api/auth/spotify-auth-link

###  REGISTER SPOTIFY USER
POST http://localhost:4040/api/auth/register-spotify-user HTTP/1.1
Content-Type: application/json

{
    "code": "AQDcpObpNOESnuJHI3srG4hpmCEp7JHJoIMFDRJOpAQI7JuwuXXzaN9EgafFUY3fsvJ9tRfN54W64uPwa2lOupfgvKyBJNdn7go9iA_onZACa4pKNHoQQMyYSDbSdz7uG1eHtxtZaNLRwpQWlwHjqubbUsaaeliGVgLJvLS0DDW3HK0uNSZw3dJrv22XO_JxhCW8iqFxwEiV5z2ixZDEs1V7o7q9i30BA6fhhXn-aqazvHy5WiA8HwCVzD-m_HULi4UCVHmkKyTLk6JkWhbhhWf0JJmKCvj0rfcQr1UGlpwT_-dfyRDk-tzfx_fWyDJx36Y4iBNW7lls3MdP-cifQujn2-ubJCq383iuFUWu0nysTqusGJQUs19hMh-rsnJ1nlou0Tk",
    "state": "6b8714a3-22be-4fd8-aa74-522283545f8d"
}
###


### GET SPOTIFY USER DEVICES

GET http://localhost:4040/api/devices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Y2ZiYjg3MjEwYWJkNDFiYzQxN2ZhMWUiLCJjcmVhdGVkX2F0IjoiMjAxOS0wNi0wOFQxMzozMDoyNi4wMzdaIiwiaWF0IjoxNTYwMDAwNjI2LCJleHAiOjE1NjAxNzM0MjZ9.OZVeuXuezYXePVc_CDAMDd3OK-hYoFq-PSgdpdgurs0

###

### CREATE ROOM

POST http://localhost:4040/api/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Y2ZiYjg3MjEwYWJkNDFiYzQxN2ZhMWUiLCJjcmVhdGVkX2F0IjoiMjAxOS0wNi0wOFQxMzozMDoyNi4wMzdaIiwiaWF0IjoxNTYwMDAwNjI2LCJleHAiOjE1NjAxNzM0MjZ9.OZVeuXuezYXePVc_CDAMDd3OK-hYoFq-PSgdpdgurs0

{
    "name": "testConcurrency12",
    "device_id": "044e30e0da6c11cf056ccbee7f295e942fe262bd"
}

###


### GET ROOM

GET http://localhost:4040/api/rooms/5cfba1a3d0c4491934f7c0ab
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Y2ZiOWYwMWVhMjVjNDE2YjVhM2EwZWIiLCJzcG90aWZ5X3Rva2VuX2V4cGlyZXNfYXQiOiIyMDE5LTA2LTA4VDEyOjQxOjUzLjg2NVoiLCJjcmVhdGVkX2F0IjoiMjAxOS0wNi0wOFQxMTo0MTo1My44NzNaIiwic3BvdGlmeV9pZCI6ImdhYnJpZWx4MjJvZ2MiLCJpYXQiOjE1NTk5OTQxMTQsImV4cCI6MTU2MDE2NjkxNH0.mECJW3nHU3U6Py-gjZvDjmzI4LuOvdTqBa92FXX7nYY


###

### REGISTER GUEST USER

POST http://localhost:4040/api/auth/register-guest-user
Content-Type: application/json


###

### SEARCH

GET http://localhost:4040/api/search/5cfba1a3d0c4491934f7c0ab/test/artist,track
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Y2ZiOWYwMWVhMjVjNDE2YjVhM2EwZWIiLCJzcG90aWZ5X3Rva2VuX2V4cGlyZXNfYXQiOiIyMDE5LTA2LTA4VDEyOjQxOjUzLjg2NVoiLCJjcmVhdGVkX2F0IjoiMjAxOS0wNi0wOFQxMTo0MTo1My44NzNaIiwic3BvdGlmeV9pZCI6ImdhYnJpZWx4MjJvZ2MiLCJpYXQiOjE1NTk5OTQxMTQsImV4cCI6MTU2MDE2NjkxNH0.mECJW3nHU3U6Py-gjZvDjmzI4LuOvdTqBa92FXX7nYY

###

### PLAY ROOM SONG

GET http://localhost:4040/api/rooms/5cfba1a3d0c4491934f7c0ab/play
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Y2ZiOWYwMWVhMjVjNDE2YjVhM2EwZWIiLCJzcG90aWZ5X3Rva2VuX2V4cGlyZXNfYXQiOiIyMDE5LTA2LTA4VDEyOjQxOjUzLjg2NVoiLCJjcmVhdGVkX2F0IjoiMjAxOS0wNi0wOFQxMTo0MTo1My44NzNaIiwic3BvdGlmeV9pZCI6ImdhYnJpZWx4MjJvZ2MiLCJpYXQiOjE1NTk5OTQxMTQsImV4cCI6MTU2MDE2NjkxNH0.mECJW3nHU3U6Py-gjZvDjmzI4LuOvdTqBa92FXX7nYY


###